# Generated by Django 6.0.4 on 2026-05-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_plants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
